3: server3.c client3.c
	gcc -o server3 server3.c -lssl -lcrypto -lcrypt -g
	gcc -o client3 client3.c -lssl -lcrypto -g

5: server5.c client5.c
	gcc -o server5 server5.c -lssl -lcrypto -lcrypt -g
	gcc -o client5 client5.c -lssl -lcrypto -g

6: server6.c client6.c
	gcc -o server6 server6.c -lssl -lcrypto -lcrypt -g
	gcc -o client6 client6.c -lssl -lcrypto -g
