21a:21a.c header.h
	@gcc -o 21a.o 21a.c -lpcap
	@sudo ./21a.o

21au:21au.c header.h
	@gcc -o 21au.o 21au.c -lpcap
	@sudo ./21au.o

21b1:21b1.c header.h
	@gcc -o 21b1.o 21b1.c -lpcap
	@sudo ./21b1.o

21b2:21b2.c header.h
	@gcc -o 21b2.o 21b2.c -lpcap
	@sudo ./21b2.o

21c:21c.c header.h
	@gcc -o 21c.o 21c.c -lpcap
	@sudo ./21c.o

22a:22a.c header.h
	@gcc -o 22a.o 22a.c
	@sudo ./22a.o

22b:22b.c header.h
	@gcc -o 22b.o 22b.c
	@sudo ./22b.o

22c:22c.c header.h
	@gcc -o 22c.o 22c.c
	@sudo ./22c.o

23:23.c header.h
	@gcc -o 23.o 23.c -lpcap
	@sudo ./23.o	

test:test.c header.h
	@gcc -o test.o test.c -lpcap
	@sudo ./test.o

clean:
	@rm *.o
